// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package vfilter

const (
	Version     = "v1.1.5"
	GitCommit   = "73fec46" // the commit JUST BEFORE the release
	VersionDate = "2020-10-26 10:35" // UTC
)

