// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package vfilter

const (
	Version = "v1.0.1"
	GitCommit = "63ed1a5" // the commit JUST BEFORE the release
	VersionDate = "2019-12-30 11:10" // UTC
)

