// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package vfilter

const (
	Version = "v1.0.3"
	GitCommit = "2a02b05" // the commit JUST BEFORE the release
	VersionDate = "2020-04-08 09:39" // UTC
)

