// Code generated by "goki generate ./..."; DO NOT EDIT.

package vxform

import (
	"goki.dev/gti"
	"goki.dev/ordmap"
)

var _ = gti.AddType(&gti.Type{
	Name:       "github.com/emer/vision/v2/vxform.Rand",
	ShortName:  "vxform.Rand",
	IDName:     "rand",
	Doc:        "Rand specifies random transforms",
	Directives: gti.Directives{},
	Fields: ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{
		{"TransX", &gti.Field{Name: "TransX", Type: "github.com/emer/etable/v2/minmax.F32", LocalType: "minmax.F32", Doc: "min -- max range of X-axis (horizontal) translations to generate (as proportion of image size)", Directives: gti.Directives{}, Tag: ""}},
		{"TransY", &gti.Field{Name: "TransY", Type: "github.com/emer/etable/v2/minmax.F32", LocalType: "minmax.F32", Doc: "min -- max range of Y-axis (vertical) translations to generate (as proportion of image size)", Directives: gti.Directives{}, Tag: ""}},
		{"Scale", &gti.Field{Name: "Scale", Type: "github.com/emer/etable/v2/minmax.F32", LocalType: "minmax.F32", Doc: "min -- max range of scales to generate", Directives: gti.Directives{}, Tag: ""}},
		{"Rot", &gti.Field{Name: "Rot", Type: "github.com/emer/etable/v2/minmax.F32", LocalType: "minmax.F32", Doc: "min -- max range of rotations to generate (in degrees)", Directives: gti.Directives{}, Tag: ""}},
	}),
	Embeds:  ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{}),
	Methods: ordmap.Make([]ordmap.KeyVal[string, *gti.Method]{}),
})

var _ = gti.AddType(&gti.Type{
	Name:       "github.com/emer/vision/v2/vxform.XForm",
	ShortName:  "vxform.XForm",
	IDName:     "x-form",
	Doc:        "XForm represents current and previous visual transformation values\nand can apply current values to transform an image.\nTransformations are performed as: rotation, scale, then translation.\nScaling crops to retain the current image size.",
	Directives: gti.Directives{},
	Fields: ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{
		{"TransX", &gti.Field{Name: "TransX", Type: "github.com/emer/emergent/v2/env.CurPrvF32", LocalType: "env.CurPrvF32", Doc: "current, prv X-axis (horizontal) translation value, as proportion of image half-size (i.e., 1 = move from center to edge)", Directives: gti.Directives{}, Tag: ""}},
		{"TransY", &gti.Field{Name: "TransY", Type: "github.com/emer/emergent/v2/env.CurPrvF32", LocalType: "env.CurPrvF32", Doc: "current, prv Y-axis (horizontal) translation value, as proportion of image half-size (i.e., 1 = move from center to edge)", Directives: gti.Directives{}, Tag: ""}},
		{"Scale", &gti.Field{Name: "Scale", Type: "github.com/emer/emergent/v2/env.CurPrvF32", LocalType: "env.CurPrvF32", Doc: "current, prv scale value", Directives: gti.Directives{}, Tag: ""}},
		{"Rot", &gti.Field{Name: "Rot", Type: "github.com/emer/emergent/v2/env.CurPrvF32", LocalType: "env.CurPrvF32", Doc: "current, prv rotation value, in degrees", Directives: gti.Directives{}, Tag: ""}},
	}),
	Embeds:  ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{}),
	Methods: ordmap.Make([]ordmap.KeyVal[string, *gti.Method]{}),
})
