// Code generated by "core generate -add-types"; DO NOT EDIT.

package vxform

import (
	"cogentcore.org/core/gti"
)

var _ = gti.AddType(&gti.Type{Name: "github.com/emer/vision/v2/vxform.Rand", IDName: "rand", Doc: "Rand specifies random transforms", Fields: []gti.Field{{Name: "TransX", Doc: "min -- max range of X-axis (horizontal) translations to generate (as proportion of image size)"}, {Name: "TransY", Doc: "min -- max range of Y-axis (vertical) translations to generate (as proportion of image size)"}, {Name: "Scale", Doc: "min -- max range of scales to generate"}, {Name: "Rot", Doc: "min -- max range of rotations to generate (in degrees)"}}})

var _ = gti.AddType(&gti.Type{Name: "github.com/emer/vision/v2/vxform.XForm", IDName: "x-form", Doc: "XForm represents current and previous visual transformation values\nand can apply current values to transform an image.\nTransformations are performed as: rotation, scale, then translation.\nScaling crops to retain the current image size.", Fields: []gti.Field{{Name: "TransX", Doc: "current, prv X-axis (horizontal) translation value, as proportion of image half-size (i.e., 1 = move from center to edge)"}, {Name: "TransY", Doc: "current, prv Y-axis (horizontal) translation value, as proportion of image half-size (i.e., 1 = move from center to edge)"}, {Name: "Scale", Doc: "current, prv scale value"}, {Name: "Rot", Doc: "current, prv rotation value, in degrees"}}})
